/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as OauthKakaoCallbackImport } from './routes/oauth.kakao.callback'

// Create Virtual Routes

const UserLazyImport = createFileRoute('/user')()
const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()
const GroupIndexLazyImport = createFileRoute('/group/')()
const GroupGroupIdLazyImport = createFileRoute('/group/$groupId')()

// Create/Update Routes

const UserLazyRoute = UserLazyImport.update({
  path: '/user',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/user.lazy').then((d) => d.Route))

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const GroupIndexLazyRoute = GroupIndexLazyImport.update({
  path: '/group/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/group.index.lazy').then((d) => d.Route))

const GroupGroupIdLazyRoute = GroupGroupIdLazyImport.update({
  path: '/group/$groupId',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/group.$groupId.lazy').then((d) => d.Route),
)

const OauthKakaoCallbackRoute = OauthKakaoCallbackImport.update({
  path: '/oauth/kakao/callback',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/user': {
      preLoaderRoute: typeof UserLazyImport
      parentRoute: typeof rootRoute
    }
    '/group/$groupId': {
      preLoaderRoute: typeof GroupGroupIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/group/': {
      preLoaderRoute: typeof GroupIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/oauth/kakao/callback': {
      preLoaderRoute: typeof OauthKakaoCallbackImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  AboutLazyRoute,
  UserLazyRoute,
  GroupGroupIdLazyRoute,
  GroupIndexLazyRoute,
  OauthKakaoCallbackRoute,
])

/* prettier-ignore-end */
