/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as OauthKakaoCallbackImport } from './routes/oauth.kakao.callback'
import { Route as GroupJoinGroupIdImport } from './routes/group/join.$groupId'
import { Route as GroupDetailGroupIdImport } from './routes/group/detail.$groupId'

// Create Virtual Routes

const UserLazyImport = createFileRoute('/user')()
const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()
const GroupIndexLazyImport = createFileRoute('/group/')()

// Create/Update Routes

const UserLazyRoute = UserLazyImport.update({
  path: '/user',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/user.lazy').then((d) => d.Route))

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const GroupIndexLazyRoute = GroupIndexLazyImport.update({
  path: '/group/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/group/index.lazy').then((d) => d.Route))

const OauthKakaoCallbackRoute = OauthKakaoCallbackImport.update({
  path: '/oauth/kakao/callback',
  getParentRoute: () => rootRoute,
} as any)

const GroupJoinGroupIdRoute = GroupJoinGroupIdImport.update({
  path: '/group/join/$groupId',
  getParentRoute: () => rootRoute,
} as any)

const GroupDetailGroupIdRoute = GroupDetailGroupIdImport.update({
  path: '/group/detail/$groupId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/user': {
      preLoaderRoute: typeof UserLazyImport
      parentRoute: typeof rootRoute
    }
    '/group/': {
      preLoaderRoute: typeof GroupIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/group/detail/$groupId': {
      preLoaderRoute: typeof GroupDetailGroupIdImport
      parentRoute: typeof rootRoute
    }
    '/group/join/$groupId': {
      preLoaderRoute: typeof GroupJoinGroupIdImport
      parentRoute: typeof rootRoute
    }
    '/oauth/kakao/callback': {
      preLoaderRoute: typeof OauthKakaoCallbackImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  AboutLazyRoute,
  UserLazyRoute,
  GroupIndexLazyRoute,
  GroupDetailGroupIdRoute,
  GroupJoinGroupIdRoute,
  OauthKakaoCallbackRoute,
])

/* prettier-ignore-end */
